// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable



namespace NotesRazorApp.Models;

/// <summary>
/// Represents a note entity with properties for its content, due date, completion status, and associated category.
/// </summary>
public partial class Note
{
    public int NoteId { get; set; }
    public string BodyText { get; set; }
    public DateTime? DueDate { get; set; }
    public bool Completed { get; set; }
    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }
}
