// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using NotesRazorApp.Classes;
using NotesRazorApp.Models;
#nullable disable

namespace NotesRazorApp.Data;

public partial class Context : DbContext
{
    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Category { get; set; }
    public virtual DbSet<Note> Note { get; set; }

    /// <summary>
    /// Configures the database context options.
    /// </summary>
    /// <param name="optionsBuilder">The builder used to configure the database context options.</param>
    /// <exception cref="Exception">Thrown when the database connection is not configured.</exception>
    /// <remarks>
    /// See Program.cs for configuration.
    /// </remarks>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            // Use the ConnectionHelpers class to configure the database connection for desktop.
            throw new Exception("Database connection is not configured.");
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.NoteConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}